apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
            name: db
  template:

    metadata:
      name: db
      labels:
        name: db
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name:  POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
        - containerPort: 5432


     